name: shopware
services:
  shopware:
    public: true
    image: okteto.dev/shopware
    build:
      context: dev-ops/docker/containers/app
      args:
          - USER_ID=1001
          - GROUP_ID=1001
    environment:
      - HTTPS=on
    ports:
      - 8000

  mysql:
    image: okteto.dev/mysql
    build:
      context: dev-ops/docker/containers/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    ports:
      - 3306
    volumes:
      - /var/lib/mysql
    resources:
      storage: 2Gi

  mailhog:
    public: true
    image: mailhog/mailhog
    ports:
      - 8025
      - 1025

  adminer:
    public: true
    image: adminer:latest
    ports:
      - 8080

  elasticsearch:
    image: elastic/elasticsearch:7.1.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - 9200
      - 9300
