name: shopware
services:
  shopware:
    public: true
    image: shyim/shopware-classic-nginx:php72
    environment:
      - HTTPS=on
    ports:
      - 8000

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=shopware
    ports:
      - 3306
    volumes:
      - /var/lib/mysql
    resources:
      storage: 2Gi

  mailhog:
    public: true
    image: mailhog/mailhog
    ports:
      - 8025
      - 1025

  adminer:
    public: true
    image: adminer:latest
    ports:
      - 8080

  elasticsearch:
    image: elastic/elasticsearch:7.1.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - 9200
      - 9300
